---
- hosts: mdf
  gather_facts: False
  vars:
    ansible_connection: network_cli
    ansible_network_os: arubaoss
    ansible_user: <USERNAME>
    ansible_password: <PASSWORD>
    ansible_python_interpreter: /usr/bin/python
  tasks:

    - name: ping tests
      shell: ping -c 1 {{ansible_host}}
      ignore_errors: true
      register: ping

    - name: Execute inital test commands
      cli_command:
        command: "show interface brief"
      register: SwitchData
      when: ping.stdout.find('1 received')!= -1
    
    - name: Output to macaddress file
      copy:
        content: "{{SwitchData}}"
        dest: "Results/{{inventory_hostname}}.pretest"
           
- hosts: idf
  gather_facts: False
  vars:
    ansible_connection: network_cli
    ansible_network_os: arubaoss
    ansible_user: <USERNAME>
    ansible_password: <PASSWORD>
    ansible_python_interpreter: /usr/bin/python
  tasks:

    - name: ping tests
      shell: ping -c 1 {{ansible_host}}
      ignore_errors: true
      register: ping

    - name: Execute inital show interface  commands
      cli_command:
        command: "show interface brief"
      register: SwitchData
      when: ping.stdout.find('1 received')!= -1
    
    - name: output file
      copy:
        content: "{{SwitchData}}"
        dest: "Results/{{inventory_hostname}}.pretest"