---
- hosts: mdf
  gather_facts: False
  vars:
    ansible_connection: network_cli
    ansible_network_os: arubaoss
    ansible_user: <USERNAME>
    ansible_password: <PASSWORD>
    ansible_python_interpreter: /usr/bin/python
  tasks:

    - name: Execute inital test commands
      cli_command:
        command: "{{ item }}"
      register: SwitchData
      with_items:
        - "show mac-address"
        - "show interface"
    
    - name: Output to macaddress file
      copy:
        content: "{{SwitchData.stdout}}"
        dest: "Results/{{inventory_hostname}}.swinfo"
           
- hosts: idf
  gather_facts: False
  vars:
    ansible_connection: network_cli
    ansible_network_os: arubaoss
    ansible_user: <USERNAME>
    ansible_password: <PASSWORD>
    ansible_python_interpreter: /usr/bin/python
  tasks:

    - name: Execute inital test commands
      cli_command:
        command: "{{ item }}"
      register: SwitchData
      with_items:
        - "show mac-address"
        - "show interface"
    
    - name: Output to macaddress file
      copy:
        content: "{{SwitchData.stdout}}"
        dest: "Results/{{inventory_hostname}}.swinfo"